server:
  port: ${SHIPMENT_SERVICE_PORT:8089}

spring:
  application:
    name: shipment-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: shipment-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
